### ISSUE TITLE
Transaction objects does not directly expose dictionary keys

### ISSUE THREAD

**Issue by slyngshede** [coolshop-com/AltaPay#26] opened 2016-01-15 08:09 UTC
When accessing the parsed values from an XML callback via the `Transaction` class, dictionary keys are not directly exposed. Instead the values must be accessed via the `transaction.__dict__['__data__']` dictionary.

`File "/opt/projects/coolpay2/coolpay/terminals/mixins/views/altapay.py", line 74, in transaction_to_payment
    remote_identifier=transaction['terminal'],
TypeError: 'Transaction' object is not subscriptable`

**Comment by HenrikOssipoff** [comment] 2016-01-15 08:17
This is by design; you should access by using ``transaction.terminal``

**Comment by slyngshede** [comment] 2016-01-15 08:28
It's unclear from the documentation that `transaction` does not expose dictionary keys  directly. Nor is it clear that the first level XML elements will be exposed directly on the `Transaction` objects.

**Comment by HenrikOssipoff** [comment] 2016-01-15 16:08
Torn on this; it's not stated anywhere the documentation that it DOES expose dictionary keys, and since it is an object, that natural way would be attributes.

I will see to add a small note in the introduction about the general wrapping of responses from AltaPay.

**Comment by HenrikOssipoff** [comment] 2016-01-18 08:03
Fixed in 0.1.dev3

**Closed by HenrikOssipoff** 2016-01-18 08:03 UTC
Labels: documentation
